# docker-compose version
version: "3"

# Broapt services
services:
  core:
    build: .
    container_name: broapt-core
    entrypoint: ["bash", "/source/init.sh"]
    environment:
      # Bro MIME whilelist
      BRO_MIME: application/x-dosexec;application/msword;application/pdf;application/vnd.android.package-archive
      # Bro file reassembly buffer size
      #FILE_BUFFER: 0xffffffffffffffff
      # Bro extract file size limit
      SIZE_LIMIT: 0
      # concurrent process limit
      CORE_CPU: 5
      # sleep interval
      CORE_INT: 10
      # force update mime2ext database
      MIME_UPDATE: 0
      # core environ
      DUMP_MIME: 1
      DUMP_PATH: /dump/
      PCAP_PATH: /pcap/
      LOGS_PATH: /var/log/bro/
    image: broapt-core
    volumes:
      - /home/traffic/pcapfile:/pcap
      # - ../../sample:/pcap
      - /home/traffic/log/extract:/dump
      # - ../dump:/dump
      - /home/traffic/log/bro:/var/log/bro
      # - ../logs:/var/log/bro
    restart: "always"
