# docker-compose version
version: "3"

# Broapt services
services:
  core:
    build: .
    container_name: broapt-core
    entrypoint: ["bash", "/source/init.sh"]
    env_file:
      - ./source/.env
    image: broapt-core
    volumes:
      - /home/traffic/pcapfile:/pcap
      # - ../../sample:/pcap
      - /home/traffic/log/extract:/dump
      # - ../dump:/dump
      - /home/traffic/log/bro:/var/log/bro
      # - ../logs:/var/log/bro
    restart: "always"
