# docker-compose version
version: "3"

# Broapt services
services:
  app:
    build: .
    container_name: broapt-app
    entrypoint: ["bash", "/source/init.sh"]
    image: broapt-app
    volumes:
      - /home/traffic/log/extract:/dump
      # - ./source/dumps:/dump
    restart: "always"
