# docker-compose version
version: "3"

# Broapt services
services:
  app:
    build: .
    container_name: broapt-app
    entrypoint: ["bash", "/source/init.sh"]
    environment:
      # BroAPT-APP environment
      ## concurrent process limit
      BROAPT_APP_CPU: 5
      ## sleep interval
      BROAPT_APP_INTERVAL: 10
      ## path to detection APIs
      BROAPT_API_ROOT: /api/
      ## path to API runtime logs
      BROAPT_API_LOGS: /var/log/bro/api/
      ## path to extract files
      BROAPT_DUMP_PATH: /dump/
      ## path to log files
      BROAPT_LOGS_PATH: /var/log/bro/
    image: broapt-app
    volumes:
      - /home/traffic/log/extract:/dump
      # - ../dump:/dump
      - /home/traffic/log/bro:/var/log/bro
      # - ../logs:/var/log/bro
      - ./vendor/api:/api/
    restart: "always"
