# docker-compose version
version: "3"

# Broapt services
services:
  app:
    build: .
    container_name: broapt-app
    entrypoint: ["bash", "/source/init.sh"]
    image: broapt-app
    volumes:
      - /home/traffic/log/extract:/dump
      # - ../dump:/dump
      - /home/traffic/log/bro:/var/log/bro
      # - ../logs:/var/log/bro
    restart: "always"
