# docker-compose version
version: "3"

# BroAPT services
services:
  app:
    build: ..
    container_name: broapt-app
    entrypoint: ["bash", "/source/init.sh"]
    # app environ
    environment:
      ## [PYTHON] force the stdout and stderr streams to be unbuffered
      PYTHONUNBUFFERED: 1
      ## concurrent process limit
      BROAPT_APP_CPU: 10
      ## sleep interval
      BROAPT_APP_INTERVAL: 10
      ## command retry
      BROAPT_MAX_RETRY: 3
      ## path to detection APIs
      BROAPT_API_ROOT: /api/
      ## path to API runtime logs
      BROAPT_API_LOGS: /var/log/bro/api/
      ## path to extract files
      BROAPT_DUMP_PATH: /dump/
      ## path to log files
      BROAPT_LOGS_PATH: /var/log/bro/
      ## daemon server
      SERVER_NAME_HOST: localhost
      SERVER_NAME_PORT: 5000
    image: broapt-app
    network_mode: "host"
    restart: "always"
    volumes:
      ## path mapping
      - /home/traffic/log/extract:/dump
      - /home/traffic/log/bro:/var/log/bro
      ## site functions
      - ../include/api:/api/
      ## change timezone
      - /etc:/etc
      - /usr/share/zoneinfo:/usr/share/zoneinfo
